### ISSUE TITLE
variable accesskey et applicationName sont inversé

### ISSUE THREAD

**Issue by j0nathan33** [myconstellation/constellation-nodejs#2]
Après investigation sur un problème de connection avec la constellation. J'ai trouvé un autre problème. Les parameter accesskey et applicationName a été inversé. Le fichier default.json que j'ai fait :

```
{
  /**
  * Constellation Configuration
  **/
  "constellation": {
    //// Constellation url
    "url" : "http://192.168.1.23:8088",
    //// Constellation Hub Access key
    "accessKey" : "asd123543254tfdsgfadfdsafsd",
    //// Your application name
    "applicationName" : "test Node JS",
    ///// Sdk Version
    "sdkVersion" : "1.8.2"
  }
}
```
J'ai rajoute la ligne suivants "console.log(that.hub.connection);" dans la fonction this.connect pour qui me donne les ligne suivants :
```
url: 'http://192.168.1.23:8088/signalr',
  qs:
   { SentinelName: 'Consumer',
     PackageName: 'asd123543254tfdsgfadfdsafsd',
     AccessKey: 'Test Node JS' },
```

J'ai inversé les ligne accessKey et applicationName et maintant, les call fonctionne sur windows

**Comment by j0nathan33** [comment]
J'ai trouvé le problème et j'ai fait une PR

**Comment by j0nathan33** [comment]
Tu peux repush la lib sur npm registry ?

**Comment by gclem** [comment]
Done
